# Generated by Django 5.1.1 on 2024-09-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AlterModelTable(
            name='visitante',
            table='visitante',
        ),
    ]
