# Generated by Django 5.1.1 on 2024-10-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.CharField(max_length=2, verbose_name='Vagas de Estacionamento')),
                ('bloco', models.CharField(max_length=1, verbose_name='Bloco')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número do Apartamento')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 'apartamento',
            },
        ),
    ]
