# Generated by Django 5.1.1 on 2024-10-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0002_remove_morador_numero_casa_morador_apartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='apartamento',
        ),
        migrations.AddField(
            model_name='morador',
            name='numero_casa',
            field=models.PositiveSmallIntegerField(default=111, verbose_name='Número do Apartamento'),
            preserve_default=False,
        ),
    ]
